### ISSUE TITLE
unix_formatting.js

### ISSUE THREAD

**Issue by devwoojin** [jcubic/electron-terminal#3]
how to use "unix_formatting"?

this.echo("\x1B[32mhello\x1B[39m")

The code below wants  green "hello" to be printed, but actually 
[32mhello
[39m

    "electron": "^22.0.0",
    "jquery.terminal": "^2.35.2"

prompt: '\x1B[32mhello\x1B[39m'

![image](https://user-images.githubusercontent.com/19814823/216290582-617b84dc-d081-49ce-8cfa-dced3a02b4f8.png)

**Comment by jcubic** [comment]
You need to edit renderer.js and add this extension.

I think this should work:

```javascript
require('jquery.terminal/js/unix_formatting')($);
```

**Comment by devwoojin** [comment]
it works!!
thank you~
